services:
  # Backend API (Production)
  backend:
    build:
      context: .
      dockerfile: songcraft-api/Dockerfile
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - DATABASE_URL=${DATABASE_URL}
      - CLERK_SECRET_KEY=${CLERK_SECRET_KEY}
      - PORT=4500
    networks:
      - songcraft_network
    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "--no-verbose",
          "--tries=1",
          "--spider",
          "http://localhost:4500/health",
        ]
      interval: 30s
      timeout: 10s
      retries: 3

  # Frontend React App (Production)
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.ssr
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - PORT=3000
      - VITE_API_URL=/api
    depends_on:
      - backend
    networks:
      - songcraft_network

  # Nginx Reverse Proxy
  nginx:
    image: nginx:alpine
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.prod.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - frontend
      - backend
    networks:
      - songcraft_network

networks:
  songcraft_network:
    driver: bridge
