services:
  # PostgreSQL Database
  db:
    image: postgres:15-alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-songcraft}
      POSTGRES_USER: ${POSTGRES_USER:-songcraft}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./songcraft-api/drizzle/0000_high_jack_flag.sql:/docker-entrypoint-initdb.d/001_init.sql
    networks:
      - songcraft_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-songcraft}"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Backend API (Production)
  backend:
    build:
      context: .
      dockerfile: songcraft-api/Dockerfile
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgresql://${POSTGRES_USER:-songcraft}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB:-songcraft_prod}
      - CLERK_SECRET_KEY=${CLERK_SECRET_KEY}
      - PORT=4500
    depends_on:
      db:
        condition: service_healthy
    networks:
      - songcraft_network
    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "--no-verbose",
          "--tries=1",
          "--spider",
          "http://localhost:4500/health",
        ]
      interval: 30s
      timeout: 10s
      retries: 3

  # Frontend React App (Production)
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.ssr
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - PORT=3000
      - VITE_API_URL=http://backend:4500
    depends_on:
      - backend
    networks:
      - songcraft_network

  # Nginx Reverse Proxy
  nginx:
    image: nginx:alpine
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.prod.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - frontend
      - backend
    networks:
      - songcraft_network

volumes:
  postgres_data:

networks:
  songcraft_network:
    driver: bridge
