services:
  db:
    image: postgres:15-alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-songcraft_dev}
      POSTGRES_USER: ${POSTGRES_USER:-songcraft}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data
      - ./songcraft-api/drizzle/0000_high_jack_flag.sql:/docker-entrypoint-initdb.d/001_init.sql
    ports:
      - "5432:5432"
    networks:
      - songcraft_dev_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-songcraft}"]
      interval: 30s
      timeout: 10s
      retries: 3

  backend:
    build:
      context: .
      dockerfile: songcraft-api/Dockerfile.dev
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgresql://${POSTGRES_USER:-songcraft}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB:-songcraft_dev}
      - CLERK_SECRET_KEY=${CLERK_SECRET_KEY}
      - PORT=4500
      # CORS Configuration for Docker environment - Allow all origins for dev
      - CORS_ORIGIN=*
      - ALLOW_HTTP=true
    ports:
      - "4500:4500"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - songcraft_dev_network
    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "--no-verbose",
          "--tries=1",
          "--spider",
          "http://localhost:4500/health",
        ]
      interval: 30s
      timeout: 10s
      retries: 3

  # TanStack Start Frontend Server
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.ssr
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - PORT=3000
      # API Configuration for Docker environment
      - VITE_API_URL=http://backend:4500
      # CORS and security
      - CORS_ORIGIN=*
      - ALLOW_HTTP=true
      # Add your auth env here, e.g. Clerk/NextAuth/etc:
      # - CLERK_SECRET_KEY=${CLERK_SECRET_KEY}
      # - AUTH_SECRET=${AUTH_SECRET}
      # - BASE_URL=https://<your-preview-host>  # optional, if your app expects it
    ports:
      - "3000:3000" # expose for debugging
    depends_on:
      - backend
    networks:
      - songcraft_dev_network

  nginx:
    image: nginx:alpine
    restart: unless-stopped
    ports:
      - "8080:80" # keep 8080 if host nginx handles 80/443
    volumes:
      - ./nginx.dev.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - frontend
      - backend
    networks:
      - songcraft_dev_network

  redis:
    image: redis:7-alpine
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - songcraft_dev_network
    command: redis-server --appendonly yes
    volumes:
      - redis_dev_data:/data

volumes:
  postgres_dev_data:
  redis_dev_data:

networks:
  songcraft_dev_network:
    driver: bridge
