services:
  # PostgreSQL Database
  db:
    image: postgres:15-alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB: songcraft_dev
      POSTGRES_USER: songcraft
      POSTGRES_PASSWORD: songcraft_dev_password
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      # Note: Drizzle migrations are now handled by the backend service

  # Frontend React App (Development)
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    environment:
      - VITE_API_URL=http://backend:4500
    depends_on:
      - backend
    restart: unless-stopped
    volumes:
      - ./songcraft/src:/app/songcraft/src
      - ./songcraft/public:/app/songcraft/public

  # Backend API (Development)
  backend:
    build:
      context: .
      dockerfile: songcraft-api/Dockerfile.dev
    ports:
      - "4500:4500"
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgresql://songcraft:songcraft_dev_password@db:5432/songcraft_dev
      - CLERK_SECRET_KEY=${CLERK_SECRET_KEY}
    depends_on:
      - db
    restart: unless-stopped
    volumes:
      - ./songcraft-api/src:/app/songcraft-api/src
      - ./songcraft-api/drizzle:/app/songcraft-api/drizzle
      - ./shared:/app/shared
    command: sh -c "npm run db:migrate:dev && npm run dev"

volumes:
  postgres_data:
