services:
  db:
    image: postgres:15-alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-songcraft_dev}
      POSTGRES_USER: ${POSTGRES_USER:-songcraft}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data
      - ./songcraft-api/drizzle/0000_high_jack_flag.sql:/docker-entrypoint-initdb.d/001_init.sql
    ports:
      - "5432:5432"
    networks:
      - songcraft_dev_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-songcraft}"]
      interval: 30s
      timeout: 10s
      retries: 3

  backend:
    build:
      context: .
      dockerfile: songcraft-api/Dockerfile.dev
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgresql://${POSTGRES_USER:-songcraft}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB:-songcraft_dev}
      - CLERK_SECRET_KEY=${CLERK_SECRET_KEY}
      - PORT=4500
    ports:
      - "4500:4500"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - songcraft_dev_network
    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "--no-verbose",
          "--tries=1",
          "--spider",
          "http://localhost:4500/health",
        ]
      interval: 30s
      timeout: 10s
      retries: 3

  # TanStack Start Frontend Server
  frontend:
    image: node:20-alpine
    restart: unless-stopped
    working_dir: /app
    volumes:
      - ./.output:/app/.output:ro
    environment:
      - NODE_ENV=development
      - PORT=3000
    ports:
      - "3000:3000"
    command: ["node", ".output/server/index.mjs"]
    depends_on:
      - backend
    networks:
      - songcraft_dev_network
    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "--no-verbose",
          "--tries=1",
          "--spider",
          "http://localhost:3000",
        ]
      interval: 30s
      timeout: 10s
      retries: 3

  nginx:
    image: nginx:alpine
    restart: unless-stopped
    ports:
      - "8080:80" # keep 8080 if host nginx is already on 80/443
      # - "8443:443"    # enable if you need TLS on the container
    volumes:
      - ./nginx.dev.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro

    depends_on:
      - backend
      - frontend
    networks:
      - songcraft_dev_network

  redis:
    image: redis:7-alpine
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - songcraft_dev_network
    command: redis-server --appendonly yes
    volumes:
      - redis_dev_data:/data

volumes:
  postgres_dev_data:
  redis_dev_data:

networks:
  songcraft_dev_network:
    driver: bridge
