/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UiSimpleRouteImport } from './routes/ui-simple'
import { Route as ThemeTestRouteImport } from './routes/theme-test'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ThemeIndexRouteImport } from './routes/theme/index'
import { Route as SongsIndexRouteImport } from './routes/songs/index'
import { Route as SessionsIndexRouteImport } from './routes/sessions/index'
import { Route as ProjectsIndexRouteImport } from './routes/projects/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as SongsNewRouteImport } from './routes/songs/new'
import { Route as SignInSsoCallbackRouteImport } from './routes/sign-in/sso-callback'
import { Route as AdminUsersRouteImport } from './routes/admin/users'
import { Route as AdminOrgsRouteImport } from './routes/admin/orgs'
import { Route as AdminAccountsRouteImport } from './routes/admin/accounts'
import { Route as SongsSongIdIndexRouteImport } from './routes/songs/$songId/index'
import { Route as SongsNewRefactoredRouteImport } from './routes/songs/new.refactored'
import { Route as SongsSongIdRecordRouteImport } from './routes/songs/$songId/record'
import { Route as SongsSongIdPackageRouteImport } from './routes/songs/$songId/package'
import { Route as SongsSongIdMidiRouteImport } from './routes/songs/$songId/midi'
import { Route as SongsSongIdLyricsRouteImport } from './routes/songs/$songId/lyrics'
import { Route as SongsSongIdCollabRouteImport } from './routes/songs/$songId/collab'
import { Route as AdminAccountsRefactoredRouteImport } from './routes/admin/accounts.refactored'
import { Route as SongsSongIdIndexRefactoredRouteImport } from './routes/songs/$songId/index.refactored'

const UiSimpleRoute = UiSimpleRouteImport.update({
  id: '/ui-simple',
  path: '/ui-simple',
  getParentRoute: () => rootRouteImport,
} as any)
const ThemeTestRoute = ThemeTestRouteImport.update({
  id: '/theme-test',
  path: '/theme-test',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ThemeIndexRoute = ThemeIndexRouteImport.update({
  id: '/theme/',
  path: '/theme/',
  getParentRoute: () => rootRouteImport,
} as any)
const SongsIndexRoute = SongsIndexRouteImport.update({
  id: '/songs/',
  path: '/songs/',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionsIndexRoute = SessionsIndexRouteImport.update({
  id: '/sessions/',
  path: '/sessions/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsIndexRoute = ProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const SongsNewRoute = SongsNewRouteImport.update({
  id: '/songs/new',
  path: '/songs/new',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInSsoCallbackRoute = SignInSsoCallbackRouteImport.update({
  id: '/sso-callback',
  path: '/sso-callback',
  getParentRoute: () => SignInRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminOrgsRoute = AdminOrgsRouteImport.update({
  id: '/admin/orgs',
  path: '/admin/orgs',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAccountsRoute = AdminAccountsRouteImport.update({
  id: '/admin/accounts',
  path: '/admin/accounts',
  getParentRoute: () => rootRouteImport,
} as any)
const SongsSongIdIndexRoute = SongsSongIdIndexRouteImport.update({
  id: '/songs/$songId/',
  path: '/songs/$songId/',
  getParentRoute: () => rootRouteImport,
} as any)
const SongsNewRefactoredRoute = SongsNewRefactoredRouteImport.update({
  id: '/refactored',
  path: '/refactored',
  getParentRoute: () => SongsNewRoute,
} as any)
const SongsSongIdRecordRoute = SongsSongIdRecordRouteImport.update({
  id: '/songs/$songId/record',
  path: '/songs/$songId/record',
  getParentRoute: () => rootRouteImport,
} as any)
const SongsSongIdPackageRoute = SongsSongIdPackageRouteImport.update({
  id: '/songs/$songId/package',
  path: '/songs/$songId/package',
  getParentRoute: () => rootRouteImport,
} as any)
const SongsSongIdMidiRoute = SongsSongIdMidiRouteImport.update({
  id: '/songs/$songId/midi',
  path: '/songs/$songId/midi',
  getParentRoute: () => rootRouteImport,
} as any)
const SongsSongIdLyricsRoute = SongsSongIdLyricsRouteImport.update({
  id: '/songs/$songId/lyrics',
  path: '/songs/$songId/lyrics',
  getParentRoute: () => rootRouteImport,
} as any)
const SongsSongIdCollabRoute = SongsSongIdCollabRouteImport.update({
  id: '/songs/$songId/collab',
  path: '/songs/$songId/collab',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAccountsRefactoredRoute = AdminAccountsRefactoredRouteImport.update({
  id: '/refactored',
  path: '/refactored',
  getParentRoute: () => AdminAccountsRoute,
} as any)
const SongsSongIdIndexRefactoredRoute =
  SongsSongIdIndexRefactoredRouteImport.update({
    id: '/songs/$songId/index/refactored',
    path: '/songs/$songId/index/refactored',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/sign-in': typeof SignInRouteWithChildren
  '/theme-test': typeof ThemeTestRoute
  '/ui-simple': typeof UiSimpleRoute
  '/admin/accounts': typeof AdminAccountsRouteWithChildren
  '/admin/orgs': typeof AdminOrgsRoute
  '/admin/users': typeof AdminUsersRoute
  '/sign-in/sso-callback': typeof SignInSsoCallbackRoute
  '/songs/new': typeof SongsNewRouteWithChildren
  '/admin': typeof AdminIndexRoute
  '/projects': typeof ProjectsIndexRoute
  '/sessions': typeof SessionsIndexRoute
  '/songs': typeof SongsIndexRoute
  '/theme': typeof ThemeIndexRoute
  '/admin/accounts/refactored': typeof AdminAccountsRefactoredRoute
  '/songs/$songId/collab': typeof SongsSongIdCollabRoute
  '/songs/$songId/lyrics': typeof SongsSongIdLyricsRoute
  '/songs/$songId/midi': typeof SongsSongIdMidiRoute
  '/songs/$songId/package': typeof SongsSongIdPackageRoute
  '/songs/$songId/record': typeof SongsSongIdRecordRoute
  '/songs/new/refactored': typeof SongsNewRefactoredRoute
  '/songs/$songId': typeof SongsSongIdIndexRoute
  '/songs/$songId/index/refactored': typeof SongsSongIdIndexRefactoredRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/sign-in': typeof SignInRouteWithChildren
  '/theme-test': typeof ThemeTestRoute
  '/ui-simple': typeof UiSimpleRoute
  '/admin/accounts': typeof AdminAccountsRouteWithChildren
  '/admin/orgs': typeof AdminOrgsRoute
  '/admin/users': typeof AdminUsersRoute
  '/sign-in/sso-callback': typeof SignInSsoCallbackRoute
  '/songs/new': typeof SongsNewRouteWithChildren
  '/admin': typeof AdminIndexRoute
  '/projects': typeof ProjectsIndexRoute
  '/sessions': typeof SessionsIndexRoute
  '/songs': typeof SongsIndexRoute
  '/theme': typeof ThemeIndexRoute
  '/admin/accounts/refactored': typeof AdminAccountsRefactoredRoute
  '/songs/$songId/collab': typeof SongsSongIdCollabRoute
  '/songs/$songId/lyrics': typeof SongsSongIdLyricsRoute
  '/songs/$songId/midi': typeof SongsSongIdMidiRoute
  '/songs/$songId/package': typeof SongsSongIdPackageRoute
  '/songs/$songId/record': typeof SongsSongIdRecordRoute
  '/songs/new/refactored': typeof SongsNewRefactoredRoute
  '/songs/$songId': typeof SongsSongIdIndexRoute
  '/songs/$songId/index/refactored': typeof SongsSongIdIndexRefactoredRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/sign-in': typeof SignInRouteWithChildren
  '/theme-test': typeof ThemeTestRoute
  '/ui-simple': typeof UiSimpleRoute
  '/admin/accounts': typeof AdminAccountsRouteWithChildren
  '/admin/orgs': typeof AdminOrgsRoute
  '/admin/users': typeof AdminUsersRoute
  '/sign-in/sso-callback': typeof SignInSsoCallbackRoute
  '/songs/new': typeof SongsNewRouteWithChildren
  '/admin/': typeof AdminIndexRoute
  '/projects/': typeof ProjectsIndexRoute
  '/sessions/': typeof SessionsIndexRoute
  '/songs/': typeof SongsIndexRoute
  '/theme/': typeof ThemeIndexRoute
  '/admin/accounts/refactored': typeof AdminAccountsRefactoredRoute
  '/songs/$songId/collab': typeof SongsSongIdCollabRoute
  '/songs/$songId/lyrics': typeof SongsSongIdLyricsRoute
  '/songs/$songId/midi': typeof SongsSongIdMidiRoute
  '/songs/$songId/package': typeof SongsSongIdPackageRoute
  '/songs/$songId/record': typeof SongsSongIdRecordRoute
  '/songs/new/refactored': typeof SongsNewRefactoredRoute
  '/songs/$songId/': typeof SongsSongIdIndexRoute
  '/songs/$songId/index/refactored': typeof SongsSongIdIndexRefactoredRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/sign-in'
    | '/theme-test'
    | '/ui-simple'
    | '/admin/accounts'
    | '/admin/orgs'
    | '/admin/users'
    | '/sign-in/sso-callback'
    | '/songs/new'
    | '/admin'
    | '/projects'
    | '/sessions'
    | '/songs'
    | '/theme'
    | '/admin/accounts/refactored'
    | '/songs/$songId/collab'
    | '/songs/$songId/lyrics'
    | '/songs/$songId/midi'
    | '/songs/$songId/package'
    | '/songs/$songId/record'
    | '/songs/new/refactored'
    | '/songs/$songId'
    | '/songs/$songId/index/refactored'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/sign-in'
    | '/theme-test'
    | '/ui-simple'
    | '/admin/accounts'
    | '/admin/orgs'
    | '/admin/users'
    | '/sign-in/sso-callback'
    | '/songs/new'
    | '/admin'
    | '/projects'
    | '/sessions'
    | '/songs'
    | '/theme'
    | '/admin/accounts/refactored'
    | '/songs/$songId/collab'
    | '/songs/$songId/lyrics'
    | '/songs/$songId/midi'
    | '/songs/$songId/package'
    | '/songs/$songId/record'
    | '/songs/new/refactored'
    | '/songs/$songId'
    | '/songs/$songId/index/refactored'
  id:
    | '__root__'
    | '/'
    | '/sign-in'
    | '/theme-test'
    | '/ui-simple'
    | '/admin/accounts'
    | '/admin/orgs'
    | '/admin/users'
    | '/sign-in/sso-callback'
    | '/songs/new'
    | '/admin/'
    | '/projects/'
    | '/sessions/'
    | '/songs/'
    | '/theme/'
    | '/admin/accounts/refactored'
    | '/songs/$songId/collab'
    | '/songs/$songId/lyrics'
    | '/songs/$songId/midi'
    | '/songs/$songId/package'
    | '/songs/$songId/record'
    | '/songs/new/refactored'
    | '/songs/$songId/'
    | '/songs/$songId/index/refactored'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SignInRoute: typeof SignInRouteWithChildren
  ThemeTestRoute: typeof ThemeTestRoute
  UiSimpleRoute: typeof UiSimpleRoute
  AdminAccountsRoute: typeof AdminAccountsRouteWithChildren
  AdminOrgsRoute: typeof AdminOrgsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  SongsNewRoute: typeof SongsNewRouteWithChildren
  AdminIndexRoute: typeof AdminIndexRoute
  ProjectsIndexRoute: typeof ProjectsIndexRoute
  SessionsIndexRoute: typeof SessionsIndexRoute
  SongsIndexRoute: typeof SongsIndexRoute
  ThemeIndexRoute: typeof ThemeIndexRoute
  SongsSongIdCollabRoute: typeof SongsSongIdCollabRoute
  SongsSongIdLyricsRoute: typeof SongsSongIdLyricsRoute
  SongsSongIdMidiRoute: typeof SongsSongIdMidiRoute
  SongsSongIdPackageRoute: typeof SongsSongIdPackageRoute
  SongsSongIdRecordRoute: typeof SongsSongIdRecordRoute
  SongsSongIdIndexRoute: typeof SongsSongIdIndexRoute
  SongsSongIdIndexRefactoredRoute: typeof SongsSongIdIndexRefactoredRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/ui-simple': {
      id: '/ui-simple'
      path: '/ui-simple'
      fullPath: '/ui-simple'
      preLoaderRoute: typeof UiSimpleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/theme-test': {
      id: '/theme-test'
      path: '/theme-test'
      fullPath: '/theme-test'
      preLoaderRoute: typeof ThemeTestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/theme/': {
      id: '/theme/'
      path: '/theme'
      fullPath: '/theme'
      preLoaderRoute: typeof ThemeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/songs/': {
      id: '/songs/'
      path: '/songs'
      fullPath: '/songs'
      preLoaderRoute: typeof SongsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sessions/': {
      id: '/sessions/'
      path: '/sessions'
      fullPath: '/sessions'
      preLoaderRoute: typeof SessionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/': {
      id: '/projects/'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/songs/new': {
      id: '/songs/new'
      path: '/songs/new'
      fullPath: '/songs/new'
      preLoaderRoute: typeof SongsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in/sso-callback': {
      id: '/sign-in/sso-callback'
      path: '/sso-callback'
      fullPath: '/sign-in/sso-callback'
      preLoaderRoute: typeof SignInSsoCallbackRouteImport
      parentRoute: typeof SignInRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/orgs': {
      id: '/admin/orgs'
      path: '/admin/orgs'
      fullPath: '/admin/orgs'
      preLoaderRoute: typeof AdminOrgsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/accounts': {
      id: '/admin/accounts'
      path: '/admin/accounts'
      fullPath: '/admin/accounts'
      preLoaderRoute: typeof AdminAccountsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/songs/$songId/': {
      id: '/songs/$songId/'
      path: '/songs/$songId'
      fullPath: '/songs/$songId'
      preLoaderRoute: typeof SongsSongIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/songs/new/refactored': {
      id: '/songs/new/refactored'
      path: '/refactored'
      fullPath: '/songs/new/refactored'
      preLoaderRoute: typeof SongsNewRefactoredRouteImport
      parentRoute: typeof SongsNewRoute
    }
    '/songs/$songId/record': {
      id: '/songs/$songId/record'
      path: '/songs/$songId/record'
      fullPath: '/songs/$songId/record'
      preLoaderRoute: typeof SongsSongIdRecordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/songs/$songId/package': {
      id: '/songs/$songId/package'
      path: '/songs/$songId/package'
      fullPath: '/songs/$songId/package'
      preLoaderRoute: typeof SongsSongIdPackageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/songs/$songId/midi': {
      id: '/songs/$songId/midi'
      path: '/songs/$songId/midi'
      fullPath: '/songs/$songId/midi'
      preLoaderRoute: typeof SongsSongIdMidiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/songs/$songId/lyrics': {
      id: '/songs/$songId/lyrics'
      path: '/songs/$songId/lyrics'
      fullPath: '/songs/$songId/lyrics'
      preLoaderRoute: typeof SongsSongIdLyricsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/songs/$songId/collab': {
      id: '/songs/$songId/collab'
      path: '/songs/$songId/collab'
      fullPath: '/songs/$songId/collab'
      preLoaderRoute: typeof SongsSongIdCollabRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/accounts/refactored': {
      id: '/admin/accounts/refactored'
      path: '/refactored'
      fullPath: '/admin/accounts/refactored'
      preLoaderRoute: typeof AdminAccountsRefactoredRouteImport
      parentRoute: typeof AdminAccountsRoute
    }
    '/songs/$songId/index/refactored': {
      id: '/songs/$songId/index/refactored'
      path: '/songs/$songId/index/refactored'
      fullPath: '/songs/$songId/index/refactored'
      preLoaderRoute: typeof SongsSongIdIndexRefactoredRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface SignInRouteChildren {
  SignInSsoCallbackRoute: typeof SignInSsoCallbackRoute
}

const SignInRouteChildren: SignInRouteChildren = {
  SignInSsoCallbackRoute: SignInSsoCallbackRoute,
}

const SignInRouteWithChildren =
  SignInRoute._addFileChildren(SignInRouteChildren)

interface AdminAccountsRouteChildren {
  AdminAccountsRefactoredRoute: typeof AdminAccountsRefactoredRoute
}

const AdminAccountsRouteChildren: AdminAccountsRouteChildren = {
  AdminAccountsRefactoredRoute: AdminAccountsRefactoredRoute,
}

const AdminAccountsRouteWithChildren = AdminAccountsRoute._addFileChildren(
  AdminAccountsRouteChildren,
)

interface SongsNewRouteChildren {
  SongsNewRefactoredRoute: typeof SongsNewRefactoredRoute
}

const SongsNewRouteChildren: SongsNewRouteChildren = {
  SongsNewRefactoredRoute: SongsNewRefactoredRoute,
}

const SongsNewRouteWithChildren = SongsNewRoute._addFileChildren(
  SongsNewRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SignInRoute: SignInRouteWithChildren,
  ThemeTestRoute: ThemeTestRoute,
  UiSimpleRoute: UiSimpleRoute,
  AdminAccountsRoute: AdminAccountsRouteWithChildren,
  AdminOrgsRoute: AdminOrgsRoute,
  AdminUsersRoute: AdminUsersRoute,
  SongsNewRoute: SongsNewRouteWithChildren,
  AdminIndexRoute: AdminIndexRoute,
  ProjectsIndexRoute: ProjectsIndexRoute,
  SessionsIndexRoute: SessionsIndexRoute,
  SongsIndexRoute: SongsIndexRoute,
  ThemeIndexRoute: ThemeIndexRoute,
  SongsSongIdCollabRoute: SongsSongIdCollabRoute,
  SongsSongIdLyricsRoute: SongsSongIdLyricsRoute,
  SongsSongIdMidiRoute: SongsSongIdMidiRoute,
  SongsSongIdPackageRoute: SongsSongIdPackageRoute,
  SongsSongIdRecordRoute: SongsSongIdRecordRoute,
  SongsSongIdIndexRoute: SongsSongIdIndexRoute,
  SongsSongIdIndexRefactoredRoute: SongsSongIdIndexRefactoredRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
